travis:
  secure:
    BINSTAR_TOKEN: bXn+0J66VJShn3bC334Kl8G0c38TW0mimv3CnQE2TUyip5Xta4FGM/JGONpp4sF+ACSU5CjooG00JOEBhpHD/u3q3aremwS8hp16T1hVT9XOxRdOhCO/5ouSh9Xdu+yzRHjBaMKcSg/DLrcBZz30CXQKzB+VxCwdbnZ54KHOc3wRvpnpH36qjxUv9/v8I7uCVae6qgAAddCqpmLGN3jtTi9YqssxZOPt0WDOibU7tBjZSFMuLadAw7FszX/rm3sOYfvOZ6sYP1F8+oDOvNAFgXWRFaMMglGHNtpYxT1FWwz75mu1UUmrz/8/QIj7HxSZb5EAOqWJmIp0WPXwvV3gh/B9HEqHM2ekuPY+AQGNOr10lZV7fjVqVME9WpAKvcQaFAVIfV5k0FTUXsW4A+RWSq+mBBap1nahYY/rRCK5BDAGA+PiLVK3un1FeBgkkxONndjk9FJ0RFv6jZy0bzvHAqOffHTsprxh6TMb/WX2rc7MSKbW4vmXKV0q2miBoaJwW0TOngZxa1v6160jIlgN1U4HefJWUOUFTXY3r5tDcw4g/0wkzVDCoe0b8ZFixEEf6wlpnvlYlTnzNt4Pi/t+UfwLCwWCCq3q+W0cbgIQaMFOX6Yli4Q88Hn4ErlEzaA3E4rSK+y82zgnaDb+OMPiiDTHJd4DB+BIfRWwDxpoxwI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
